services:
  - type: web
    name: userservice
    -env: dotnet
    plan: free
    buildCommand: "dotnet publish UserService.API/UserService.API.csproj -c Release -o out"
    startCommand: "dotnet out/UserService.API.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: "Staging"
      - key: ConnectionStrings__MyConnectionString
        value: "Server=SACHIN\\SQLEXPRESS;Database=UserDb;User Id=sa;Password=Sachin11@567;TrustServerCertificate=True;"
      - key: JwtSettings__Issuer
        value: "UserService.API"
      - key: JwtSettings__SecretKey
        value: "fPXxcJw8TW5sA+S4rl4tIPcKk+oXAqoRBo+1s2yjUS4="
